version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: timetracker-db
    environment:
      POSTGRES_DB: timetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d timetracker" ]
      interval: 5s
      timeout: 5s
      retries: 10

  task_time_tracker_api:
    build: .
    container_name: timetracker-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/timetracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_SQL_INIT_MODE: never
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  postgres_data: